.PHONY: default build clean 
build:
	make -C ./filesharer build
	make -C ./messenger build
	make -C ./remoter build
clean:
	make -C ./filesharer clean
	make -C ./messenger clean
	make -C ./remoter clean
