settings:
  messages_capacity: 2048
  work_size_bits: 20
  language: ENG
  pseudonym: i4sRNRXw_qoCv-RCBF_VjZy8nnOKYafI
  storage_key: u4Dz9PvNzn3DOItsrSWMODIrUwK5tmsw
logging:
- info
- warn
- erro
address:
  interface: :9591
  incoming: :9592
connection: service:9572
