version: "3"
services:
  recv_hls_service:
    build:
      context: ./../../../../
      dockerfile: examples/anonymity/echo_service/_service/Dockerfile
    networks:
      - local-network
  recv_hls:
    build:
      context: ./../../../../
      dockerfile: cmd/hidden_lake/service/Dockerfile
    environment:
      - SERVICE_PATH=examples/anonymity/echo_service/prod_test/recv_hls
      - SERVICE_PRIV=examples/anonymity/_keys/4096/priv_recv.key
    networks:
      - local-network
  send_hls:
    build:
      context: ./../../../../
      dockerfile: cmd/hidden_lake/service/Dockerfile
    environment:
      - SERVICE_PATH=examples/anonymity/echo_service/prod_test/send_hls
      - SERVICE_PRIV=examples/anonymity/_keys/4096/priv_send.key
    ports:
      - 7572:7572
  other_hls:
    build:
      context: ./../../../../
      dockerfile: cmd/hidden_lake/service/Dockerfile
    deploy:
        replicas: 3
    environment:
      - SERVICE_PATH=examples/anonymity/echo_service/prod_test/other_hls
      - SERVICE_PRIV=examples/anonymity/echo_service/prod_test/other_hls/priv.key
networks:
  local-network:
    driver: bridge
