version: "3"
services:
  node1_hlc:
    build:
      context: ./../../../
      dockerfile: cmd/hidden_lake/composite/Dockerfile
    environment:
      - SERVICE_PATH=examples/secure_network/messenger/node1_hlm
      - SERVICE_KEY=examples/secure_network/_keys/4096/priv_node1.key
    ports:
      - 8080:8080
    networks:
      - hidden-lake
  node2_hlc:
    build:
      context: ./../../../
      dockerfile: cmd/hidden_lake/composite/Dockerfile
    environment:
      - SERVICE_PATH=examples/secure_network/messenger/node2_hlm
      - SERVICE_KEY=examples/secure_network/_keys/4096/priv_node2.key
    ports:
      - 7070:7070
      - 7572:7572
    networks:
      - hidden-lake
networks:
  hidden-lake:
    driver: bridge
