version: "3"
services:
  service:
    build:
      context: ./../../../../../
      dockerfile: cmd/hidden_lake/adapters/common/service/Dockerfile
    environment:
      - SERVICE_ADDR=:6060
      - LOG_ENABLED=false
    networks:
      - hidden-lake
  recv_hls_service:
    build:
      context: ./../../../../../
      dockerfile: examples/echo_service/docker/_service/Dockerfile
    networks:
      - recv-local-network
  recv_hlc:
    build:
      context: ./../../../../../
      dockerfile: cmd/hidden_lake/composite/Dockerfile
    environment:
      - SERVICE_PATH=examples/echo_service/docker/secret_channel/common/recv_hls
      - SERVICE_KEY=examples/echo_service/secret_channel/recv_hls/priv.key
    networks:
      - recv-local-network
      - hidden-lake
  send_hlc:
    build:
      context: ./../../../../../
      dockerfile: cmd/hidden_lake/composite/Dockerfile
    environment:
      - SERVICE_PATH=examples/echo_service/docker/secret_channel/common/send_hls
      - SERVICE_KEY=examples/echo_service/secret_channel/send_hls/priv.key
    ports:
      - 7572:7572
    networks:
      - hidden-lake
networks:
  recv-local-network:
    driver: bridge
  hidden-lake:
    driver: bridge
