version: "3"
services:
  hl_service:
    build:
      context: ./../../
      dockerfile: cmd/hidden_lake/service/Dockerfile
    volumes:
      - ./_mounted:/mounted
    ports:
      - "9571:9571"
      - "9572:9572"
  hl_traffic:
    build:
      context: ./../../
      dockerfile: cmd/hidden_lake/traffic/Dockerfile
    volumes:
      - ./_mounted:/mounted
    ports:
      - "9581:9581"
    depends_on:
      - hl_service
  hl_messenger:
    build:
      context: ./../../
      dockerfile: cmd/hidden_lake/messenger/Dockerfile
    volumes:
      - ./_mounted:/mounted
    ports:
      - "9591:9591"
      - "9592:9592"
    depends_on:
      - hl_service
      - hl_traffic
