version: "3"
services:
  service:
    build:
      context: ./../../
      dockerfile: cmd/hidden_lake/service/Dockerfile
    environment:
      SERVICE_PATH: /mounted
    volumes:
      - ./_mounted:/mounted
    ports:
      - "9571:9571"
      - "9572:9572"
    networks:
      - hidden-lake
  traffic:
    build:
      context: ./../../
      dockerfile: cmd/hidden_lake/traffic/Dockerfile
    environment:
      SERVICE_PATH: /mounted
    volumes:
      - ./_mounted:/mounted
    ports:
      - "9581:9581"
    networks:
      - hidden-lake
  messenger:
    build:
      context: ./../../
      dockerfile: cmd/hidden_lake/messenger/Dockerfile
    environment:
      SERVICE_PATH: /mounted
    volumes:
      - ./_mounted:/mounted
    ports:
      - "9591:9591"
      - "9592:9592"
    networks:
      - hidden-lake
networks:
  hidden-lake:
    driver: bridge
