version: "3"
services:
  middle_hlt:
    build:
      context: ./../../../
      dockerfile: cmd/hidden_lake/helpers/traffic/Dockerfile
    environment:
      - SERVICE_PATH=examples/anon_messenger/group/middle_hlt
    networks:
      - hidden-lake
  node1_hlc:
    build:
      context: ./../../../
      dockerfile: cmd/hidden_lake/composite/Dockerfile
    environment:
      - SERVICE_PATH=examples/anon_messenger/group/node1_hlm
      - SERVICE_KEY=examples/anon_messenger/_keys/4096/priv_node1.key
    ports:
      - 8080:8080
    networks:
      - hidden-lake
  node2_hlc:
    build:
      context: ./../../../
      dockerfile: cmd/hidden_lake/composite/Dockerfile
    environment:
      - SERVICE_PATH=examples/anon_messenger/group/node2_hlm
      - SERVICE_KEY=examples/anon_messenger/_keys/4096/priv_node1.key
    ports:
      - 7070:7070
      - 7572:7572
    networks:
      - hidden-lake
  node3_hlc:
    build:
      context: ./../../../
      dockerfile: cmd/hidden_lake/composite/Dockerfile
    environment:
      - SERVICE_PATH=examples/anon_messenger/group/node3_hlm
      - SERVICE_KEY=examples/anon_messenger/_keys/4096/priv_node1.key
    ports:
      - 6060:6060
    networks:
      - hidden-lake
networks:
  hidden-lake:
    driver: bridge
