.PHONY: default build clean 
build:
	make -C ./loader build
	make -C ./encryptor build
	make -C ./adapters build
	make -C ./traffic build
clean:
	make -C ./loader clean
	make -C ./encryptor clean
	make -C ./adapters clean
	make -C ./traffic clean
