version: "3"
services:
  node1_hlc:
    build:
      context: ./../../../../../
      dockerfile: cmd/hidden_lake/composite/Dockerfile
    environment:
      - SERVICE_PATH=examples/anonymity/filesharer/secret_channel/chatingar/node1_hlf
    ports:
      - 8572:8572
      - 8080:8080
    networks:
      - hidden-lake
  node2_hlc:
    build:
      context: ./../../../../../
      dockerfile: cmd/hidden_lake/composite/Dockerfile
    environment:
      - SERVICE_PATH=examples/anonymity/filesharer/secret_channel/chatingar/node2_hlf
    ports:
      - 7070:7070
    networks:
      - hidden-lake
networks:
  hidden-lake:
    driver: bridge
