version: "3"
services:
  recv_hlc:
    build:
      context: ./../../../../
      dockerfile: cmd/hidden_lake/composite/Dockerfile
    environment:
      - SERVICE_PATH=examples/anonymity/remoter/routing/recv_hlc
      - SERVICE_PRIV=examples/anonymity/_keys/4096/priv_node1.key
    networks:
      - hidden-lake
  send_hls:
    build:
      context: ./../../../../
      dockerfile: cmd/hidden_lake/service/Dockerfile
    environment:
      - SERVICE_PATH=examples/anonymity/remoter/routing/send_hls
      - SERVICE_PRIV=examples/anonymity/_keys/4096/priv_node2.key
    ports:
      - 7572:7572
    networks:
      - hidden-lake
  middle_hlt_1:
    build:
      context: ./../../../../
      dockerfile: cmd/hidden_lake/helpers/traffic/Dockerfile
    environment:
      - SERVICE_PATH=examples/anonymity/remoter/routing/middle_hlt_1
    networks:
      - hidden-lake
  middle_hlt_2:
    build:
      context: ./../../../../
      dockerfile: cmd/hidden_lake/helpers/traffic/Dockerfile
    environment:
      - SERVICE_PATH=examples/anonymity/remoter/routing/middle_hlt_2
    networks:
      - hidden-lake
  middle_hlt_3:
    build:
      context: ./../../../../
      dockerfile: cmd/hidden_lake/helpers/traffic/Dockerfile
    environment:
      - SERVICE_PATH=examples/anonymity/remoter/routing/middle_hlt_3
    networks:
      - hidden-lake
networks:
  hidden-lake:
    driver: bridge
