version: "3"
services:
  node1_hlc:
    build:
      context: ./../../../../
      dockerfile: cmd/hidden_lake/composite/Dockerfile
    environment:
      - SERVICE_PATH=examples/anon_messenger/docker/prod_test/node1_hlm
      - SERVICE_KEY=examples/anon_messenger/prod_test/node1_hlm/priv.key
    ports:
      - 8080:8080
  node2_hlc:
    build:
      context: ./../../../../
      dockerfile: cmd/hidden_lake/composite/Dockerfile
    environment:
      - SERVICE_PATH=examples/anon_messenger/docker/prod_test/node2_hlm
      - SERVICE_KEY=examples/anon_messenger/prod_test/node2_hlm/priv.key
    ports:
      - 7070:7070
