version: "3"
services:
  service:
    build:
      context: ./../../../../
      dockerfile: cmd/hidden_lake/helpers/adapters/common/service/Dockerfile
    environment:
      - SERVICE_ADDR=:6060
      - LOG_ENABLED=false
    networks:
      - hidden-lake
  node1_hlc:
    build:
      context: ./../../../../
      dockerfile: cmd/hidden_lake/composite/Dockerfile
    environment:
      - SERVICE_PATH=examples/anon_messenger/docker/secret_channel/node1_hlm
      - SERVICE_KEY=examples/anon_messenger/secret_channel/node1_hlm/priv.key
    ports:
      - 8080:8080
    networks:
      - hidden-lake
  node2_hlc:
    build:
      context: ./../../../../
      dockerfile: cmd/hidden_lake/composite/Dockerfile
    environment:
      - SERVICE_PATH=examples/anon_messenger/docker/secret_channel/node2_hlm
      - SERVICE_KEY=examples/anon_messenger/secret_channel/node2_hlm/priv.key
    ports:
      - 7070:7070
    networks:
      - hidden-lake
networks:
  hidden-lake:
    driver: bridge
