version: "3"
services:
  recv_hls_service:
    build:
      context: ./../../../../
      dockerfile: examples/anonymity/echo_service/_service/Dockerfile
    networks:
      - local-network
  recv_hls:
    build:
      context: ./../../../../
      dockerfile: cmd/hidden_lake/service/Dockerfile
    environment:
      - SERVICE_PATH=examples/anonymity/echo_service/routing/recv_hls
      - SERVICE_PRIV=examples/anonymity/_keys/4096/priv_recv.key
    networks:
      - local-network
      - hidden-lake
  send_hls:
    build:
      context: ./../../../../
      dockerfile: cmd/hidden_lake/service/Dockerfile
    environment:
      - SERVICE_PATH=examples/anonymity/echo_service/routing/send_hls
      - SERVICE_PRIV=examples/anonymity/_keys/4096/priv_send.key
    ports:
      - 7572:7572
    networks:
      - hidden-lake
  middle_hlt_1:
    build:
      context: ./../../../../
      dockerfile: cmd/hidden_lake/helpers/traffic/Dockerfile
    environment:
      - SERVICE_PATH=examples/anonymity/echo_service/routing/middle_hlt_1
    networks:
      - hidden-lake
  middle_hlt_2:
    build:
      context: ./../../../../
      dockerfile: cmd/hidden_lake/helpers/traffic/Dockerfile
    environment:
      - SERVICE_PATH=examples/anonymity/echo_service/routing/middle_hlt_2
    networks:
      - hidden-lake
  middle_hlt_3:
    build:
      context: ./../../../../
      dockerfile: cmd/hidden_lake/helpers/traffic/Dockerfile
    environment:
      - SERVICE_PATH=examples/anonymity/echo_service/routing/middle_hlt_3
    networks:
      - hidden-lake
networks:
  local-network:
    driver: bridge
  hidden-lake:
    driver: bridge
