version: "3"
services:
  service:
    build:
      context: ./../../../../../
      dockerfile: cmd/hidden_lake/adapters/common/cmd/service/Dockerfile
    environment:
      - SERVICE_ADDR=:6060
      - LOG_ENABLED=false
    networks:
      - hidden-lake
  recv_hlc:
    build:
      context: ./../../../../../
      dockerfile: cmd/hidden_lake/composite/Dockerfile
    environment:
      - SERVICE_PATH=examples/anonymity/remoter/secret_channel/common/recv_hlc
    networks:
      - hidden-lake
  send_hlc:
    build:
      context: ./../../../../../
      dockerfile: cmd/hidden_lake/composite/Dockerfile
    environment:
      - SERVICE_PATH=examples/anonymity/remoter/secret_channel/common/send_hlc
    ports:
      - 7572:7572
    networks:
      - hidden-lake
networks:
  hidden-lake:
    driver: bridge
