.PHONY: default build clean

default: build 
build:
	make -C ./hidden_lake build
	make -C ./micro_anon build
	make -C ./tools build
clean:
	make -C ./hidden_lake clean
	make -C ./micro_anon clean
	make -C ./tools clean
