version: "3"
services:
  node1_hlc:
    build:
      context: ./../../../
      dockerfile: cmd/hidden_lake/composite/Dockerfile
    environment:
      - SERVICE_PATH=examples/anon_messenger/prod_test/node1_hlm
      - SERVICE_PRIV=examples/anon_messenger/_keys/4096/priv_node1.key
      - SERVICE_PASW=examples/anon_messenger/_keys/pasw/pasw_node1.key
    ports:
      - 8080:8080
  node2_hlc:
    build:
      context: ./../../../
      dockerfile: cmd/hidden_lake/composite/Dockerfile
    environment:
      - SERVICE_PATH=examples/anon_messenger/prod_test/node2_hlm
      - SERVICE_PRIV=examples/anon_messenger/_keys/4096/priv_node2.key
      - SERVICE_PASW=examples/anon_messenger/_keys/pasw/pasw_node2.key
    ports:
      - 7070:7070
      - 7572:7572
