version: "3"
services:
  recv_hls_service:
    build:
      context: ./../../../../
      dockerfile: examples/echo_service/docker/_service/Dockerfile
    networks:
      - local-network
  recv_hls:
    build:
      context: ./../../../../
      dockerfile: cmd/hidden_lake/service/Dockerfile
    environment:
      - SERVICE_PATH=examples/echo_service/docker/default/recv_hls
      - SERVICE_KEY=examples/echo_service/default/recv_hls/priv.key
    networks:
      - local-network
      - hidden-lake
  send_hls:
    build:
      context: ./../../../../
      dockerfile: cmd/hidden_lake/service/Dockerfile
    environment:
      - SERVICE_PATH=examples/echo_service/docker/default/send_hls
      - SERVICE_KEY=examples/echo_service/default/send_hls/priv.key
    ports:
      - 7572:7572
    networks:
      - hidden-lake
  middle_hlt_1:
    build:
      context: ./../../../../
      dockerfile: cmd/hidden_lake/helpers/traffic/Dockerfile
    environment:
      - SERVICE_PATH=examples/echo_service/docker/routing/middle_hlt_1
    networks:
      - hidden-lake
  middle_hlt_2:
    build:
      context: ./../../../../
      dockerfile: cmd/hidden_lake/helpers/traffic/Dockerfile
    environment:
      - SERVICE_PATH=examples/echo_service/docker/routing/middle_hlt_2
    networks:
      - hidden-lake
  middle_hlt_3:
    build:
      context: ./../../../../
      dockerfile: cmd/hidden_lake/helpers/traffic/Dockerfile
    environment:
      - SERVICE_PATH=examples/echo_service/docker/routing/middle_hlt_3
    networks:
      - hidden-lake
networks:
  local-network:
    driver: bridge
  hidden-lake:
    driver: bridge
