version: "3"
services:
  service:
    build:
      context: ./../../../../
      dockerfile: cmd/hidden_lake/helpers/adapters/common/service/Dockerfile
    environment:
      - SERVICE_ADDR=:6060
      - LOG_ENABLED=false
    networks:
      - hidden-lake
  recv_hls_service:
    build:
      context: ./../../../../
      dockerfile: examples/echo_service/docker/_service/Dockerfile
    networks:
      - recv-local-network
  recv_producer:
    build:
      context: ./../../../../
      dockerfile: cmd/hidden_lake/helpers/adapters/common/producer/Dockerfile
    environment:
      - SERVICE_ADDR=service:6060
      - INCOMING_ADDR=:8082
      - LOG_ENABLED=true
    networks:
      - recv-local-network
      - hidden-lake
  recv_consumer:
    build:
      context: ./../../../../
      dockerfile: cmd/hidden_lake/helpers/adapters/common/consumer/Dockerfile
    environment:
      - SERVICE_ADDR=service:6060
      - TRAFFIC_ADDR=recv_hlc:8582
      - LOG_ENABLED=true
    networks:
      - recv-local-network
      - hidden-lake
  recv_hlc:
    build:
      context: ./../../../../
      dockerfile: cmd/hidden_lake/composite/Dockerfile
    environment:
      - SERVICE_PATH=examples/echo_service/docker/secret_channel/recv_hls
      - SERVICE_KEY=examples/echo_service/secret_channel/recv_hls/priv.key
    networks:
      - recv-local-network
  send_producer:
    build:
      context: ./../../../../
      dockerfile: cmd/hidden_lake/helpers/adapters/common/producer/Dockerfile
    environment:
      - SERVICE_ADDR=service:6060
      - INCOMING_ADDR=:7072
      - LOG_ENABLED=true
    networks:
      - send-local-network
      - hidden-lake
  send_consumer:
    build:
      context: ./../../../../
      dockerfile: cmd/hidden_lake/helpers/adapters/common/consumer/Dockerfile
    environment:
      - SERVICE_ADDR=service:6060
      - TRAFFIC_ADDR=send_hlc:7582
      - LOG_ENABLED=true
    networks:
      - send-local-network
      - hidden-lake
  send_hlc:
    build:
      context: ./../../../../
      dockerfile: cmd/hidden_lake/composite/Dockerfile
    environment:
      - SERVICE_PATH=examples/echo_service/docker/secret_channel/send_hls
      - SERVICE_KEY=examples/echo_service/secret_channel/send_hls/priv.key
    ports:
      - 7572:7572
    networks:
      - send-local-network
networks:
  recv-local-network:
    driver: bridge
  send-local-network:
    driver: bridge
  hidden-lake:
    driver: bridge
