.PHONY: default build clean

default: build 
build:
	make -C ./keygen build
	make -C ./keysplit build
	make -C ./pmanager build
clean:
	make -C ./keygen clean
	make -C ./keysplit clean
	make -C ./pmanager clean
