name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Applications installing...
      run: sudo apt-get update && sudo apt-get install -y wget gcc make git
    - name: Golang installing v1.23...
      run: wget https://go.dev/dl/go1.23.0.linux-amd64.tar.gz && tar -C /opt -xzf go1.23.0.linux-amd64.tar.gz
    - name: Go-peer downloading...
      run: git clone --depth=1 https://github.com/number571/go-peer.git
    - name: Go-peer deps installing...
      run: export PATH=$PATH:$(go env GOPATH)/bin && make install-deps -C go-peer
    - name: Go-peer lint/test running...
      run: export PATH=$PATH:$(go env GOPATH)/bin && make -C go-peer
