name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Ubuntu updating...
      run: sudo apt-get update 
    - name: Programs installing...
      run: sudo apt-get install -y wget gcc make tar
    - name: Golang installing...
      run: wget https://dl.google.com/go/go1.16.linux-amd64.tar.gz
    - name: Golang unpacking...
      run: sudo tar -C /opt -xzf go1.16.linux-amd64.tar.gz
    - name: Environment setting_test...
      run: ls
    - name: Environment setting...
      run: export PATH="${PATH}:/opt/go/bin"
    - name: Go-peer test running...
      run: make
