name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Ubuntu updating...
      run: sudo apt-get update 
    - name: Applications installing...
      run: sudo apt-get install -y wget gcc make git
    - name: Golang installing...
      run: wget https://dl.google.com/go/go1.16.linux-amd64.tar.gz
    - name: Golang unpacking...
      run: sudo tar -C /opt -xzf go1.16.linux-amd64.tar.gz
    - name: Environment setting...
      run: export PATH="${PATH}:/opt/go/bin"
    - name: Go-peer installing...
      run: git clone https://github.com/number571/go-peer.git
    - name: Go-peer test running...
      run: make -C go-peer
