name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Ubuntu updating
      run: apt-get update 
    - name: GCC installing
      run: apt-get install -y wget gcc make
    - name: Golang installing
      run: >-
        wget https://dl.google.com/go/go1.16.linux-amd64.tar.gz && \
        tar -C /opt -xzf go1.16.linux-amd64.tar.gz
    - name: Environment setting
      run: export PATH="${PATH}:/opt/go/bin"
    - name: Go-peer test running
      run: make
