version: "3"
services:
  service:
    build:
      context: ./../../../../../
      dockerfile: cmd/hidden_lake/adapters/common/cmd/service/Dockerfile
    environment:
      - SERVICE_ADDR=:6060
      - LOG_ENABLED=false
    networks:
      - hidden-lake
  node1_hlc:
    build:
      context: ./../../../../../
      dockerfile: cmd/hidden_lake/composite/Dockerfile
    environment:
      - SERVICE_PATH=examples/anonymity/messenger/secret_channel/common/node1_hlm
    ports:
      - 8080:8080
    networks:
      - hidden-lake
  node2_hlc:
    build:
      context: ./../../../../../
      dockerfile: cmd/hidden_lake/composite/Dockerfile
    environment:
      - SERVICE_PATH=examples/anonymity/messenger/secret_channel/common/node2_hlm
    ports:
      - 7070:7070
      - 7572:7572
    networks:
      - hidden-lake
networks:
  hidden-lake:
    driver: bridge
